[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader"

[deploy]
startCommand = "php -S 0.0.0.0:${PORT:-8080} -t public/"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
PHP_VERSION = "8.2"