[build]
builder = "nixpacks"

[deploy]
startCommand = "php -S 0.0.0.0:${PORT:-8080} -t public/"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[service]
internal_port = 8080